blank_issues_enabled: true
contact_links:
  - name: 💬 Questions & discussions
    url: https://github.com/microsoft/vscode-java-dependency/discussions
    about: Ask usage questions or start a discussion instead of filing a bug.
