name: $(Date:yyyyMMdd).$(Rev:r)
variables:
  - name: Codeql.Enabled
    value: true
schedules:
  - cron: 0 0 * * *
    branches:
      include:
        - refs/heads/main
resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/main
    - repository: MicroBuildTemplate
      type: git
      name: 1ESPipelineTemplates/MicroBuildTemplate
trigger: none
extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    pool:
      name: VSEngSS-MicroBuild2022-1ES
    settings:
      networkIsolationPolicy: Permissive
    stages:
      - stage: Build
        jobs:
          - job: Job_1
            displayName: Agent job 1
            templateContext:
              mb:
                signing:
                  enabled: true
                  signType: real
                  signWithProd: true
                  zipSources: false
                  feedSource: 'https://mseng.pkgs.visualstudio.com/DefaultCollection/_packaging/MicroBuildToolset/nuget/v3/index.json'
              outputs:
                - output: pipelineArtifact
                  artifactName: extension
                  targetPath: $(Build.ArtifactStagingDirectory)
                  displayName: "Publish Artifact: extension"
            steps:
              - checkout: self
                clean: true
                fetchTags: true
              - task: NodeTool@0
                displayName: Use Node 20.x
                inputs:
                  versionSpec: 20.x
              # The image does not have jdk preinstalled, we need to download it first.
              - task: PowerShell@2
                displayName: Download JDK 21
                inputs:
                  targetType: 'inline'
                  script: |-
                    New-Item -ItemType Directory -Path "$env:AGENT_TEMPDIRECTORY\downloadjdk"
                    Invoke-WebRequest -Uri "https://aka.ms/download-jdk/microsoft-jdk-21-windows-x64.zip" -OutFile "$env:AGENT_TEMPDIRECTORY\downloadjdk\microsoft-jdk-21-windows-x64.zip"
              - task: JavaToolInstaller@0
                displayName: Use Java 21
                inputs:
                  versionSpec: "21"
                  jdkArchitectureOption: x64
                  jdkSourceOption: LocalDirectory
                  jdkFile: $(Agent.TempDirectory)/downloadjdk/microsoft-jdk-21-windows-x64.zip
                  jdkDestinationDirectory: $(Agent.ToolsDirectory)/ms-jdk21
              - script: java --version
                displayName: 'Check Java installation'
              - task: Npm@1
                displayName: npm install
                inputs:
                  verbose: false
              - task: CmdLine@2
                displayName: npx gulp build_server
                inputs:
                  targetType: inline
                  script: |-
                    # Build the jars to the server folder.
                    npm run build-server
              - task: PowerShell@2
                displayName: 'Edit ddsignfiles config'
                inputs:
                  targetType: 'inline'
                  script: |
                    $signConfigPath = Join-Path $env:MBSIGN_APPFOLDER "ddsignfilesconfig.xml"
                    $base64 = "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiID8+DQo8RERTaWduQ29uZmlnU2V0dGluZ3M+DQogIDxBcHByb3ZlcnM+bWlrZWJvbjtieWVuPC9BcHByb3ZlcnM+DQogIDxCYXRjaFNpemU+NzU8L0JhdGNoU2l6ZT4NCiAgPFN1Ym1pc3Npb25UaW1lb3V0SW5NaW51dGVzPjE4MDwvU3VibWlzc2lvblRpbWVvdXRJbk1pbnV0ZXM+DQogIDxUb3RhbE51bWJlck9mUGFyYWxsZWxUaHJlYWRzPjU8L1RvdGFsTnVtYmVyT2ZQYXJhbGxlbFRocmVhZHM+DQogIDxUZXN0U2lnblRocmVhZENvdW50PjEwPC9UZXN0U2lnblRocmVhZENvdW50Pg0KICA8VGVzdFNpZ25Ob0NvcHk+dHJ1ZTwvVGVzdFNpZ25Ob0NvcHk+DQogIDxDb3B5RmlsZVJldHJ5SW50ZXJ2YWxJbk1pbnV0ZXM+NTwvQ29weUZpbGVSZXRyeUludGVydmFsSW5NaW51dGVzPg0KICA8UmV0cnlJbnRlcnZhbEluTWludXRlcz4yPC9SZXRyeUludGVydmFsSW5NaW51dGVzPg0KICA8RXh0ZW5zaW9uTGlzdD5leGU7ZGxsO2NhdDtjYWI7b2N4O3ZicztybGw7dnNpO2pzO21zaTttc3A7eHNuO3BzZjt4bGFtO3hsc2I7eGxzbTt4bHRtO3BvdG07cHBzbTtwcHRtO3BzbTE7ZG9jbTtkb3RtO3R0ZjtvdGY7cHMxO3BzMXhtbDtjcGw7c3RnO211aTt4YXA7YXBweDtvbGI7dnNpeDt2c21hbjt3aW5tZDt4bWw7bnVwa2c7cHk7cHlkO2FwcGxpY2F0aW9uO21hbmlmZXN0PC9FeHRlbnNpb25MaXN0Pg0KICA8UGVuZGluZ0pvYlJldHJ5SW50ZXJ2YWxJblNlY29uZHM+MTU8L1BlbmRpbmdKb2JSZXRyeUludGVydmFsSW5TZWNvbmRzPg0KICA8U2lnbmluZ1NlcnZpY2U+RVNSUENsaWVudDwvU2lnbmluZ1NlcnZpY2U+DQogIDxTaWduaW5nU2VydmljZVR5cGU+TXVsdGlUZW5hbnRTaWduaW5nPC9TaWduaW5nU2VydmljZVR5cGU+DQogIDxTaWduaW5nQXV0aGVudGljYXRpb25UeXBlPkNlcnRpZmljYXRlPC9TaWduaW5nQXV0aGVudGljYXRpb25UeXBlPg0KICA8RVNSUEF6dXJlVGVuYW50PnBtZTwvRVNSUEF6dXJlVGVuYW50Pg0KICA8Q2VydGlmaWNhdGVTaWduaW5nPnRydWU8L0NlcnRpZmljYXRlU2lnbmluZz4NCjwvRERTaWduQ29uZmlnU2V0dGluZ3M+"
                    $bytes = [Convert]::FromBase64String($base64)
                    $asciiString = [System.Text.Encoding]::ASCII.GetString($bytes)
                    Set-Content -Path $signConfigPath -Value $asciiString
              - task: PowerShell@2
                displayName: Sign Jars
                inputs:
                  targetType: 'inline'
                  script: |-
                    $files = Get-ChildItem -Path . -Recurse -Filter "com.microsoft.jdtls.ext.*.jar"
                    foreach ($file in $files) {
                        $fileName = $file.Name
                        & dotnet "$env:MBSIGN_APPFOLDER\DDSignFiles.dll" /file:"$fileName" /certs:100010171
                    }
                  workingDirectory: 'server'
              - task: CmdLine@2
                displayName: Replace AI Key
                inputs:
                  script: npx json@9.0.6 -I -f package.json -e "this.aiKey=\"%AI_KEY%\""
              - task: PowerShell@2
                displayName: Update package.json
                inputs:
                  targetType: inline
                  script: |-
                    node ./scripts/prepare-nightly-build.js
                    Move-Item -Path "./package.insiders.json" -Destination "./package.json" -Force
              - script: npx @vscode/vsce@latest package -o extension.vsix
                displayName: 'vsce package'
              ### Copy files for APIScan
              - task: CopyFiles@2
                displayName: "Copy Files for APIScan"
                inputs:
                  Contents: "*.vsix"
                  TargetFolder: $(Agent.TempDirectory)/APIScanFiles
                condition: and(succeeded(), ne(variables['DisableAPIScan'], 'true'))
              ### Run latest version of APIScan listed at https://www.1eswiki.com/wiki/APIScan_Build_Task
              - task: APIScan@2
                displayName: Run APIScan
                inputs:
                  softwareFolder: $(Agent.TempDirectory)/APIScanFiles
                  softwareName: "vscode-java-dependency"
                  softwareVersionNum: "$(Build.BuildId)"
                  isLargeApp: false
                  toolVersion: "Latest"
                condition: and(succeeded(), ne(variables['DisableAPIScan'], 'true'))
                env:
                  AzureServicesAuthConnectionString: runAs=App;AppId=$(ApiScanClientId);TenantId=$(ApiScanTenant);AppKey=$(ApiScanSecret)
              - script: npx @vscode/vsce@latest generate-manifest -i extension.vsix -o extension.manifest
                displayName: 'Generate extension manifest'
              - script: copy extension.manifest extension.signature.p7s
                displayName: 'Prepare manifest for signing'
              - task: CmdLine@2
                displayName: Sign extension
                inputs:
                  script: dotnet %MBSIGN_APPFOLDER%/ddsignfiles.dll /file:extension.signature.p7s /certs:4014052
              - task: CopyFiles@2
                displayName: "Copy Files to: $(Build.ArtifactStagingDirectory)"
                inputs:
                  Contents: |
                    extension.vsix
                    extension.manifest
                    extension.signature.p7s
                  TargetFolder: $(Build.ArtifactStagingDirectory)
