name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linuxUI:
    name: Linux-UI
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2

    - name: Setup Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y libxkbfile-dev pkg-config libsecret-1-dev libxss1 dbus xvfb libgtk-3-0 libgbm1
        sudo /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 3

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 16
        
    - name: Install Node.js modules
      run: npm install

    - name: Install VSCE
      run: npm install -g vsce

    - name: Build OSGi bundle
      run: npm run build-server

    - name: Build VSIX file
      run: vsce package

    - name: UI Test
      continue-on-error: true
      id: test
      run: DISPLAY=:99 npm run test-ui

    - name: Retry UI Test 1
      continue-on-error: true
      if: steps.test.outcome=='failure'
      id: retry1
      run: |
        git reset --hard
        git clean -fd
        DISPLAY=:99 npm run test-ui

    - name: Retry UI Test 2
      continue-on-error: true
      if: steps.retry1.outcome=='failure'
      id: retry2
      run: |
        git reset --hard
        git clean -fd
        DISPLAY=:99 npm run test-ui

    - name: Set test status
      if: ${{ steps.test.outcome=='failure' && steps.retry1.outcome=='failure' && steps.retry2.outcome=='failure' }}
      run: |
        echo "Tests failed"
        exit 1

    - name: Print language server Log
      if: ${{ failure() }}
      run: find ./test-resources/settings/User/workspaceStorage/*/redhat.java/jdt_ws/.metadata/.log -print -exec cat '{}' \;;
